# Generated by Django 6.0.2 on 2026-02-06 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên loài")),
                (
                    "characteristics",
                    models.TextField(blank=True, verbose_name="Đặc tính"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UrbanTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Mã cây"),
                ),
                ("height", models.FloatField(verbose_name="Chiều cao (m)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TOT", "Tốt"),
                            ("SAU_BENH", "Sâu bệnh"),
                            ("NGUY_HIEM", "Nguy hiểm"),
                        ],
                        max_length=50,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Vĩ độ (Y)")),
                ("longitude", models.FloatField(verbose_name="Kinh độ (X)")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_map.treespecies",
                        verbose_name="Loài cây",
                    ),
                ),
            ],
        ),
    ]
