# Generated by Django 6.0.2 on 2026-02-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urbantree",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="tree_images/", verbose_name="Hình ảnh"
            ),
        ),
    ]
