# Generated by Django 6.0.2 on 2026-02-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0002_urbantree_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày thực hiện")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CAT_TIA", "Cắt tỉa cành"),
                            ("BON_PHAN", "Bón phân"),
                            ("PHUN_THUOC", "Phun thuốc trừ sâu"),
                            ("KIEM_TRA", "Kiểm tra định kỳ"),
                        ],
                        max_length=200,
                        verbose_name="Công việc",
                    ),
                ),
                (
                    "performer",
                    models.CharField(max_length=100, verbose_name="Người thực hiện"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú/Kết quả")),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_map.urbantree",
                        verbose_name="Cây xanh",
                    ),
                ),
            ],
        ),
    ]
