# Generated by Django 6.0.3 on 2026-03-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0003_maintenancelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="treespecies",
            name="inspection_frequency_days",
            field=models.PositiveIntegerField(
                default=90, verbose_name="Chu kỳ kiểm tra (ngày)"
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="is_pest_prone",
            field=models.BooleanField(default=False, verbose_name="Dễ sâu bệnh"),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="watering_frequency_days",
            field=models.PositiveIntegerField(
                default=7, verbose_name="Chu kỳ tưới nước (ngày)"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CAT_TIA", "Cắt tỉa cành"),
                    ("BON_PHAN", "Bón phân"),
                    ("PHUN_THUOC", "Phun thuốc trừ sâu"),
                    ("KIEM_TRA", "Kiểm tra định kỳ"),
                    ("TUOI_NUOC", "Tưới nước"),
                ],
                max_length=200,
                verbose_name="Công việc",
            ),
        ),
    ]
