# Generated by Django 6.0.3 on 2026-03-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0004_treespecies_inspection_frequency_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treespecies",
            name="is_drought_sensitive",
            field=models.BooleanField(default=False, verbose_name="Nhạy cảm hạn hán"),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="is_fall_prone",
            field=models.BooleanField(default=False, verbose_name="Dễ đổ/gãy"),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="is_fast_growing",
            field=models.BooleanField(
                default=False, verbose_name="Mọc nhanh (cần cắt tỉa)"
            ),
        ),
        migrations.AddField(
            model_name="treespecies",
            name="is_invasive_roots",
            field=models.BooleanField(default=False, verbose_name="Rễ xâm lấn"),
        ),
    ]
