# Generated by Django 6.0.3 on 2026-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0005_treespecies_is_drought_sensitive_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên vùng")),
                (
                    "color",
                    models.CharField(
                        default="#1abc9c", max_length=7, verbose_name="Màu hiển thị"
                    ),
                ),
                ("polygon_json", models.TextField(verbose_name="Polygon GeoJSON")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
