# Generated by Django 6.0.2 on 2026-03-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0006_managementzone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ADD_TREE", "Thêm cây"),
                            ("EDIT_TREE", "Sửa cây"),
                            ("DELETE_TREE", "Xóa cây"),
                            ("ADD_SPECIES", "Thêm loài"),
                            ("EDIT_SPECIES", "Sửa loài"),
                            ("DELETE_SPECIES", "Xóa loài"),
                            ("ADD_MAINTENANCE", "Thêm chăm sóc"),
                            ("BULK_MAINTENANCE", "Chăm sóc hàng loạt"),
                            ("UPLOAD_IMAGE", "Cập nhật ảnh"),
                        ],
                        max_length=32,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Đối tượng"
                    ),
                ),
                (
                    "entity_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Mã/Tên đối tượng"
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="Chi tiết")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thao tác",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký hoạt động",
                "verbose_name_plural": "Nhật ký hoạt động",
                "ordering": ["-created_at"],
            },
        ),
    ]
