# Generated by Django 6.0.2 on 2026-04-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0007_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="tree_images/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mô tả ảnh"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tải lên"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="public_map.urbantree",
                        verbose_name="Cây xanh",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hình ảnh cây",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
