# Generated by Django 6.0.2 on 2026-04-01 11:00
# Manual migration for adding tree measurement fields
# This migration must be applied after database permissions are available

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_map', '0008_treeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbantree',
            name='trunk_radius',
            field=models.FloatField(blank=True, help_text='Đo bán kính thân cây tính bằng cm', null=True, verbose_name='Bán kính thân cây (cm)'),
        ),
        migrations.AddField(
            model_name='urbantree',
            name='canopy_diameter',
            field=models.FloatField(blank=True, help_text='Đo đường kính vòm cây tính bằng mét', null=True, verbose_name='Đường kính vòm che phủ (m)'),
        ),
        migrations.AddField(
            model_name='urbantree',
            name='planting_year',
            field=models.IntegerField(blank=True, help_text='Năm cây được trồng', null=True, verbose_name='Năm trồng cây'),
        ),
    ]
