# Generated by Django 6.0.2 on 2026-04-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0009_urbantree_add_measurements"),
    ]

    operations = [
        # Add new fields to MaintenanceLog for action-specific data
        migrations.AddField(
            model_name="maintenancelog",
            name="fertilizer_name",
            field=models.CharField(
                blank=True,
                help_text="Dùng khi bón phân",
                max_length=150,
                null=True,
                verbose_name="Tên phân bón",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="pesticide_name",
            field=models.CharField(
                blank=True,
                help_text="Dùng khi phun thuốc",
                max_length=150,
                null=True,
                verbose_name="Tên thuốc",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="water_amount",
            field=models.FloatField(
                blank=True,
                help_text="Dùng khi tưới nước",
                null=True,
                verbose_name="Lượng nước (lít)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="measurement_height",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật chiều cao cây nếu kiểm tra",
                null=True,
                verbose_name="Chiều cao (m)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="measurement_trunk_radius",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật bán kính thân nếu kiểm tra",
                null=True,
                verbose_name="Bán kính thân (cm)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="measurement_canopy_diameter",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật đường kính vòm nếu kiểm tra",
                null=True,
                verbose_name="Đường kính vòm (m)",
            ),
        ),
    ]
# Generated by Django 6.0.2 on 2026-04-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0009_urbantree_add_measurements"),
    ]

    operations = [
        # Add new fields to MaintenanceLog for action-specific data
        migrations.AddField(
            model_name="maintenancelog",
            name="fertilizer_name",
            field=models.CharField(
                blank=True,
                help_text="Dùng khi bón phân",
                max_length=150,
                null=True,
                verbose_name="Tên phân bón",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="pesticide_name",
            field=models.CharField(
                blank=True,
                help_text="Dùng khi phun thuốc",
                max_length=150,
                null=True,
                verbose_name="Tên thuốc",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="water_amount",
            field=models.FloatField(
                blank=True,
                help_text="Dùng khi tưới nước",
                null=True,
                verbose_name="Lượng nước (lít)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="measurement_height",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật chiều cao cây nếu kiểm tra",
                null=True,
                verbose_name="Chiều cao (m)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="measurement_trunk_radius",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật bán kính thân nếu kiểm tra",
                null=True,
                verbose_name="Bán kính thân (cm)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="measurement_canopy_diameter",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật đường kính vòm nếu kiểm tra",
                null=True,
                verbose_name="Đường kính vòm (m)",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ADD_TREE", "Thêm cây"),
                    ("EDIT_TREE", "Sửa cây"),
                    ("DELETE_TREE", "Xóa cây"),
                    ("ADD_SPECIES", "Thêm loài"),
                    ("EDIT_SPECIES", "Sửa loài"),
                    ("DELETE_SPECIES", "Xóa loài"),
                    ("ADD_MAINTENANCE", "Thêm chăm sóc"),
                    ("BULK_MAINTENANCE", "Chăm sóc hàng loạt"),
                    ("UPLOAD_IMAGE", "Cập nhật ảnh"),
                    ("DELETE_IMAGE", "Xóa ảnh"),
                ],
                max_length=32,
                verbose_name="Hành động",
            ),
        ),
    ]
