# Generated by Django 6.0.2 on 2026-04-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0010_add_maintenance_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tên chất lượng đất"
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("fertile", "🌱 Đất tốt/Đất màu mỡ"),
                            ("compacted", "🪨 Đất xây dựng/Nén chặt"),
                            ("acidic", "🧪 Đất chua"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Loại đất",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "growth_impact",
                    models.CharField(
                        choices=[
                            ("slows_growth", "Chậm phát triển"),
                            ("normal", "Bình thường"),
                            ("accelerated", "Phát triển nhanh"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Tác động đến tốc độ phát triển",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chất lượng đất",
            },
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CAT_TIA", "Cắt tỉa cành"),
                    ("BON_PHAN", "Bón phân"),
                    ("PHUN_THUOC", "Phun thuốc trừ sâu"),
                    ("KIEM_TRA", "Kiểm tra định kỳ"),
                    ("TUOI_NUOC", "Tưới nước"),
                ],
                max_length=200,
                verbose_name="Công việc",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="measurement_canopy_diameter",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật diện tích vòm nếu kiểm tra",
                null=True,
                verbose_name="Diện tích vòm (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="measurement_trunk_radius",
            field=models.FloatField(
                blank=True,
                help_text="Cập nhật đường kính thân nếu kiểm tra",
                null=True,
                verbose_name="Đường kính thân (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="urbantree",
            name="canopy_diameter",
            field=models.FloatField(
                blank=True,
                help_text="Diện tích vòm che phủ tính bằng mét vuông",
                null=True,
                verbose_name="Diện tích vòm che phủ (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="urbantree",
            name="trunk_radius",
            field=models.FloatField(
                blank=True,
                help_text="Đo đường kính thân cây tại ngực tính bằng cm",
                null=True,
                verbose_name="Đường kính thân cây (cm)",
            ),
        ),
        migrations.AddField(
            model_name="urbantree",
            name="soil_qualities",
            field=models.ManyToManyField(
                blank=True,
                related_name="trees",
                to="public_map.soilquality",
                verbose_name="Chất lượng đất",
            ),
        ),
    ]
