# Generated by Django 6.0.2 on 2026-04-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_map", "0011_soilquality_alter_maintenancelog_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên quận/huyện"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Mã quận/huyện"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quận/Huyện",
                "verbose_name_plural": "Quận/Huyện",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="urbantree",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trees",
                to="public_map.district",
                verbose_name="Quận/Huyện",
            ),
        ),
        migrations.CreateModel(
            name="UserManagedDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_by_users",
                        to="public_map.district",
                        verbose_name="Quận/Huyện",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_districts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quận/Huyện được quản lý",
                "verbose_name_plural": "Quận/Huyện được quản lý",
                "unique_together": {("user", "district")},
            },
        ),
    ]
